[package]
name = "aqara_rs"
version = "0.1.0"
authors = ["meteorcat <guixin2010@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "0.2.36"
json = "0.12.4"
